Models/Staff/StaffDepartmentEnum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AFCHIntranet.Models.Staff
{
    public enum StaffDepartmentEnum
    {
        办公室,
        后勤部,
        护理部,
        膳食部,
        医疗部
    }
}

Models/Staff/StaffPositionStateEnum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AFCHIntranet.Models.Staff
{
    public enum StaffPositionStateEnum
    {
        试用,
        短期,
        长期,               
        离职,
    }
}

Pages/Account/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Account;
using AFCHIntranet.Models.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Account
{
    public class CreateModel : PageModel
    {
        private readonly LoginService _loginService;

        public CreateModel(LoginService loginService)
        {
            _loginService = loginService;
        }

        public void OnGet()
        {
        }

        [BindProperty]
        public LoginUser NewUser { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var query = await _loginService.CreateLoginUser(NewUser);
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            return RedirectToPage("/Account/Index");
        }
    }
}

Pages/Account/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Account;
using AFCHIntranet.Models.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Account
{
    public class EditModel : PageModel
    {
        private readonly LoginService _loginService;

        public EditModel(LoginService loginService)
        {
            _loginService = loginService;
        }

        public async Task<IActionResult> OnGet(int id)
        {
            var query = await _loginService.GetLoginUserById(id);

            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            EditUser = query.Value;
            return Page();
        }

        [BindProperty]
        public LoginUser EditUser { get; set; }

        public async Task<IActionResult> OnPostEditUserRole()
        {
            var query = await _loginService.EditLoginUserRoleName(EditUser.Id, EditUser.RoleName);
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            return RedirectToPage("/Account/Index");
        }

        public async Task<IActionResult> OnPostEditUserPassword()
        {
            var query = await _loginService.EditLoginUserPassword(EditUser.Id, EditUser.Password);
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            return RedirectToPage("/Account/Index");
        }

        public async Task<IActionResult> OnPostDeleteUser()
        {
            var query = await _loginService.DeleteLoginUserById(EditUser.Id);
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            return RedirectToPage("/Account/Index");
        }
    }
}

Pages/Elder/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Elder;
using AFCHIntranet.Models.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Elder
{
    public class DetailsModel : PageModel
    {
        private readonly ElderService _elderService;

        public DetailsModel(ElderService elderService)
        {
            this._elderService = elderService;
        }

        [BindProperty]
        public Elder_Detail Elder { get; set; }

        [BindProperty]
        public Elder_Family Family { get; set; }

        public async Task<IActionResult> OnGet(int id, string returnPage)
        {
            ViewData["ReturnPage"] = returnPage;

            var query = await _elderService.GetElderAndFamilyById(id);
            if (query.IsSuccess)
            {
                Elder = query.Elder;
                Family = query.Family;
                return Page();
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }
        }
     
    }
}

Pages/Staff/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Services;
using AFCHIntranet.Models.Staff;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Staff
{
    public class CreateModel : PageModel
    {
        private readonly StaffService _staffService;

        public CreateModel(StaffService staffService)
        {
            this._staffService = staffService;
        }

        public void OnGet()
        {
        }

        [BindProperty]
        public Staff_Detail Staff { get; set; }

        public async Task<IActionResult> OnPost()
        {
            var query = await _staffService.CreateNew(Staff);
            if (query.IsSuccess)
            {
                return RedirectToPage("Details", new { id = query.Staff.Id });
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }
        }
    }
}

Pages/Staff/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Services;
using AFCHIntranet.Models.Staff;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Staff
{
    public class DetailsModel : PageModel
    {
        private readonly StaffService _staffService;

        public DetailsModel(StaffService staffService)
        {
            this._staffService = staffService;
        }

        public async Task OnGet(int id)
        {
            var query = await _staffService.GetStaffById(id);
            if (query.IsSuccess)
            {
                Staff = query.Staff;
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
            }
        }

        public Staff_Detail Staff { get; set; }
    }
}

Pages/Staff/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Services;
using AFCHIntranet.Models.Staff;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Staff
{
    public class EditModel : PageModel
    {
        private readonly StaffService _staffService;

        public EditModel(StaffService staffService)
        {
            this._staffService = staffService;
        }

        public async Task OnGet(int id)
        {
            var query = await _staffService.GetStaffById(id);
            if (query.IsSuccess)
            {
                Staff = query.Staff;
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
            }
        }

        [BindProperty]
        public Staff_Detail Staff { get; set; }

        public async Task<IActionResult> OnPostUpdateStaff()
        {
            var query = await _staffService.UpdateStaff(Staff);
            if (query.IsSuccess)
            {
                return RedirectToPage("Details", new { id = query.Staff.Id });
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
                Staff = query.Staff;
                return Page();
            }
        }
    }
}

Pages/Staff/IndexDelete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Staff
{
    public class IndexDeleteModel : PageModel
    {
        private readonly StaffService _staffService;

        public IndexDeleteModel(StaffService staffService)
        {
            this._staffService = staffService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnGetAllListJson()
        {
            var query = await _staffService.GetAllList();
            if (query.IsSuccess)
            {
                return new JsonResult(query.GetListJsonData());
            }
            else
            {
                return new JsonResult(query.ErrorJsonData());
            }
        }

        public async Task<IActionResult> OnGetToDelete(int id)
        {
            var query = await _staffService.DeleteStaff(id);
            if (query.IsSuccess)
            {
                return RedirectToPage();
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }
        }
    }
}

Pages/Staff/Create.cshtml
@page
@model AFCHIntranet.Pages.Staff.CreateModel
@{
}


<fieldset class="layui-elem-field layui-field-title">
    <legend>新增员工</legend>
</fieldset>

<div asp-validation-summary="All" class="layui-bg-red"></div>

<form class="layui-form" method="post" onsubmit="SubmitLoading()">
    <!--资料-->
    <fieldset class="layui-elem-field layui-field-box">
        <legend>员工资料</legend>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.WorkStartDate"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.WorkStartDate" readonly class="layui-input" lay-verify="required" lay-reqtext="必填项" id="date1">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.PositionState"></label>
            <div class="layui-input-block">
                <input type="radio" value="@StaffPositionStateEnum.试用.ToString()" title="@StaffPositionStateEnum.试用.ToString()" asp-for="Staff.PositionState" checked>
                <input type="radio" value="@StaffPositionStateEnum.短期.ToString()" title="@StaffPositionStateEnum.短期.ToString()" asp-for="Staff.PositionState">
                <input type="radio" value="@StaffPositionStateEnum.长期.ToString()" title="@StaffPositionStateEnum.长期.ToString()" asp-for="Staff.PositionState">
                <input type="radio" value="@StaffPositionStateEnum.离职.ToString()" title="@StaffPositionStateEnum.离职.ToString()" asp-for="Staff.PositionState">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Department"></label>
            <div class="layui-input-inline">
                <select asp-for="Staff.Department">
                    <option value="@StaffDepartmentEnum.办公室.ToString()" selected>@StaffDepartmentEnum.办公室.ToString()</option>
                    <option value="@StaffDepartmentEnum.后勤部.ToString()">@StaffDepartmentEnum.后勤部.ToString()</option>
                    <option value="@StaffDepartmentEnum.护理部.ToString()">@StaffDepartmentEnum.护理部.ToString()</option>
                    <option value="@StaffDepartmentEnum.膳食部.ToString()">@StaffDepartmentEnum.膳食部.ToString()</option>
                    <option value="@StaffDepartmentEnum.医疗部.ToString()">@StaffDepartmentEnum.医疗部.ToString()</option>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Name"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Name" class="layui-input" lay-verify="required" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Sex"></label>
            <div class="layui-input-block">
                <input type="radio" value="男" title="男" checked="" asp-for="Staff.Sex">
                <input type="radio" value="女" title="女" asp-for="Staff.Sex">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Phone"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Phone" class="layui-input" lay-verify="phone" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Marital"></label>
            <div class="layui-input-block">
                <input type="radio" value="未婚" title="未婚" checked="" asp-for="Staff.Marital">
                <input type="radio" value="已婚" title="已婚" asp-for="Staff.Marital">
                <input type="radio" value="离异" title="离异" asp-for="Staff.Marital">
                <input type="radio" value="丧偶" title="丧偶" asp-for="Staff.Marital">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Identity"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Identity" class="layui-input" lay-verify="identity" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.IDAddress"></label>
            <div class="layui-input-block">
                <input type="text" asp-for="Staff.IDAddress" class="layui-input" lay-verify="required" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.HomeAddress"></label>
            <div class="layui-input-block">
                <input type="text" asp-for="Staff.HomeAddress" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.JiGuan"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.JiGuan" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.MinZu"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.MinZu" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Education"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Education" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Skill"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Skill" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.RomNumber"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.RomNumber" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-form-text">
            <label class="layui-form-label" asp-for="Staff.Remark"></label>
            <div class="layui-input-block">
                <textarea type="text" asp-for="Staff.Remark" class="layui-textarea"></textarea>
            </div>
        </div>

        <!--紧急联系人-->
        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.FamilyName"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.FamilyName" class="layui-input" lay-verify="required" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.FamilyPhone"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.FamilyPhone" class="layui-input" lay-verify="required" lay-reqtext="必填项">
            </div>
        </div>
    </fieldset>

    <!--提交按钮-->
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button type="submit" class="layui-btn" lay-submit="">保存</button>
        </div>
    </div>
</form>

<!-- submit loading-->
<div class="submit_loading" style="display:none">
    <div class="loading_show">
        <img src="~/intranet/images/loading.gif" />
        <p class="loading_context">正在提交，请稍后。。。</p>
    </div>
</div>

@section Scripts{
    <script>
        Page_Staff_Create();
    </script>
}

Pages/Staff/Download.cshtml
@page
@model AFCHIntranet.Pages.Staff.DownloadModel
@{
    var error = ViewData["Error"];
}

<fieldset class="layui-elem-field layui-field-box">
    <legend>下载 员工资料</legend>

    <div class=" layui-inline">
        <label class="layui-form-label">下载Excel</label>
        <a class="layui-btn layui-btn-primary layui-btn-sm" asp-page-handler="ExcelWorking">在职人员</a>
    </div>

</fieldset>

@*系统管理员上传Excel数据*@
@if (User.IsInRole(LoginUserRole.Administrator))
{

    <fieldset class="layui-elem-field layui-field-box">
        <legend>上传 员工资料</legend>

        <p>非系统管理员勿用</p>
        <form enctype="multipart/form-data" method="post" asp-page-handler="UploadExcel">
            @*<div class=" layui-inline">
                    <label class="layui-form-label"></label>
                    <a class="layui-btn layui-btn-primary layui-btn-sm" asp-page-handler="ExcelTemplet">下载Excel模板</a>
                </div>*@
            <div class=" layui-inline">
                <label class="layui-form-label">上传Excel</label>
                <input type="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" name="uploadExcel" />
            </div>
            <div>
                <input type="submit" class="layui-btn layui-btn-primary" value="提交" />
            </div>
        </form>
    </fieldset>
}


@if (error != null)
{
    <script>

            alert('@Html.Raw(error)');
    </script>
}

Pages/Staff/Edit.cshtml
@page
@model AFCHIntranet.Pages.Staff.EditModel
@{
    var staff = Model.Staff;
}

<fieldset class="layui-elem-field layui-field-title">
    <legend>编辑员工</legend>
</fieldset>

<div asp-validation-summary="All" class="layui-bg-red"></div>

<form class="layui-form" method="post" asp-page-handler="UpdateStaff" onsubmit="SubmitLoading()">
    <!--资料-->
    <fieldset class="layui-elem-field layui-field-box">
        <legend>员工资料</legend>

        <input type="hidden" asp-for="Staff.Id" />

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Name"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Name" class="layui-input" lay-verify="required" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Sex"></label>
            <div class="layui-input-block">
                <input type="radio" value="男" title="男" checked="" asp-for="Staff.Sex">
                <input type="radio" value="女" title="女" asp-for="Staff.Sex">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Phone"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Phone" class="layui-input" lay-verify="phone" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Marital"></label>
            <div class="layui-input-block">
                <input type="radio" value="未婚" title="未婚" checked="" asp-for="Staff.Marital">
                <input type="radio" value="已婚" title="已婚" asp-for="Staff.Marital">
                <input type="radio" value="离异" title="离异" asp-for="Staff.Marital">
                <input type="radio" value="丧偶" title="丧偶" asp-for="Staff.Marital">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Identity"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Identity" class="layui-input" lay-verify="identity" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.IDAddress"></label>
            <div class="layui-input-block">
                <input type="text" asp-for="Staff.IDAddress" class="layui-input" lay-verify="required" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.HomeAddress"></label>
            <div class="layui-input-block">
                <input type="text" asp-for="Staff.HomeAddress" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.JiGuan"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.JiGuan" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.MinZu"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.MinZu" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Education"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Education" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Skill"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.Skill" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.RomNumber"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.RomNumber" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.Department"></label>
            <div class="layui-input-inline">
                <select asp-for="Staff.Department">
                    <option value="@StaffDepartmentEnum.办公室.ToString()">@StaffDepartmentEnum.办公室.ToString()</option>
                    <option value="@StaffDepartmentEnum.后勤部.ToString()">@StaffDepartmentEnum.后勤部.ToString()</option>
                    <option value="@StaffDepartmentEnum.护理部.ToString()">@StaffDepartmentEnum.护理部.ToString()</option>
                    <option value="@StaffDepartmentEnum.膳食部.ToString()">@StaffDepartmentEnum.膳食部.ToString()</option>
                    <option value="@StaffDepartmentEnum.医疗部.ToString()">@StaffDepartmentEnum.医疗部.ToString()</option>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.PositionState"></label>
            <div class="layui-input-block">
                <input type="radio" value="@StaffPositionStateEnum.试用.ToString()" title="@StaffPositionStateEnum.试用.ToString()" asp-for="Staff.PositionState">
                <input type="radio" value="@StaffPositionStateEnum.短期.ToString()" title="@StaffPositionStateEnum.短期.ToString()" asp-for="Staff.PositionState">
                <input type="radio" value="@StaffPositionStateEnum.长期.ToString()" title="@StaffPositionStateEnum.长期.ToString()" asp-for="Staff.PositionState">
                <input type="radio" value="@StaffPositionStateEnum.离职.ToString()" title="@StaffPositionStateEnum.离职.ToString()" asp-for="Staff.PositionState">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.WorkStartDate"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.WorkStartDate" readonly class="layui-input" lay-verify="required" lay-reqtext="必填项" id="date1">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.ContractStartDate"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.ContractStartDate" readonly class="layui-input" id="date2">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.ContractTerm"></label>
            <div class="layui-input-inline">
                <input type="number" asp-for="Staff.ContractTerm" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.LeftDate"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.LeftDate" readonly class="layui-input" id="date3">
            </div>
        </div>

        <div class="layui-form-item layui-form-text">
            <label class="layui-form-label" asp-for="Staff.Remark"></label>
            <div class="layui-input-block">
                <textarea type="text" asp-for="Staff.Remark" class="layui-textarea"></textarea>
            </div>
        </div>

        <!--紧急联系人-->
        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.FamilyName"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.FamilyName" class="layui-input" lay-verify="required" lay-reqtext="必填项">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label" asp-for="Staff.FamilyPhone"></label>
            <div class="layui-input-inline">
                <input type="text" asp-for="Staff.FamilyPhone" class="layui-input" lay-verify="required" lay-reqtext="必填项">
            </div>
        </div>
    </fieldset>

    <!--提交按钮-->
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button type="submit" class="layui-btn" lay-submit="">保存</button>
        </div>
    </div>
</form>

<!--返回-->
<div class="layui-form-item">
    <div class="layui-input-block">
        <a class="layui-btn layui-btn-sm" asp-page="Details" asp-route-id="@staff.Id">返回</a>
    </div>
</div>

<!-- submit loading-->
<div class="submit_loading" style="display:none">
    <div class="loading_show">
        <img src="~/intranet/images/loading.gif" />
        <p class="loading_context">正在提交，请稍后。。。</p>
    </div>
</div>

@section Scripts{
    <script>
        Page_Staff_Edit();
    </script>
}

Pages/Staff/IndexDelete.cshtml
@page
@model AFCHIntranet.Pages.Staff.IndexDeleteModel
@{
}

<div asp-validation-summary="All" class="layui-bg-red"></div>

<!-- layui_table1 -->
<div class="layui-row">
    <table class="layui-hide" id="table1" lay-filter="table1"></table>
</div>

@section Scripts{
    <!--表格行操作模板-->
    <script type="text/html" id="caoZuoTpl">
        <a class="layui-btn layui-btn-xs" href="/Staff/Details?id={{d.id}}">详细</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" href="/Staff/IndexDelete?handler=ToDelete&id={{d.id}}" onclick="javascript:return confirm('确定删除? 不可恢复!')">删除</a>
    </script>

    <!--layui table-->
    <script>
        Page_Staff_IndexDelete();
    </script>

} <!--Scripts section 结尾-->