Models/Account/LoginUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AFCHIntranet.Models.Account
{
    public class LoginUser
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "用户名不能为空")]
        [MaxLength(10)]
        public string Name { get; set; }

        [Required(ErrorMessage = "密码不能为空")]
        [MaxLength(10)]
        public string Password { get; set; }

        [MaxLength(20)]
        public string RoleName { get; set; }

        public int LoginErrorCount { get; set; }

        public bool AccountLocked { get; set; }

        #region NotMapped
        [NotMapped]
        public const int AllowErrorCount = 5;
        #endregion

    }
}

Models/Account/LoginUserRole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AFCHIntranet.Models.Account
{
    public class LoginUserRole
    {
        public const string Administrator = "Administrator";

        public const string PowerUser = "PowerUser";

        public const string User = "User";
    }
}

Pages/Account/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Account;
using AFCHIntranet.Models.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Account
{
    public class CreateModel : PageModel
    {
        private readonly LoginService _loginService;

        public CreateModel(LoginService loginService)
        {
            _loginService = loginService;
        }

        public void OnGet()
        {
        }

        [BindProperty]
        public LoginUser NewUser { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var query = await _loginService.CreateLoginUser(NewUser);
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            return RedirectToPage("/Account/Index");
        }
    }
}

Pages/Account/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Account;
using AFCHIntranet.Models.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Account
{
    public class EditModel : PageModel
    {
        private readonly LoginService _loginService;

        public EditModel(LoginService loginService)
        {
            _loginService = loginService;
        }

        public async Task<IActionResult> OnGet(int id)
        {
            var query = await _loginService.GetLoginUserById(id);

            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            EditUser = query.Value;
            return Page();
        }

        [BindProperty]
        public LoginUser EditUser { get; set; }

        public async Task<IActionResult> OnPostEditUserRole()
        {
            var query = await _loginService.EditLoginUserRoleName(EditUser.Id, EditUser.RoleName);
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            return RedirectToPage("/Account/Index");
        }

        public async Task<IActionResult> OnPostEditUserPassword()
        {
            var query = await _loginService.EditLoginUserPassword(EditUser.Id, EditUser.Password);
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            return RedirectToPage("/Account/Index");
        }

        public async Task<IActionResult> OnPostDeleteUser()
        {
            var query = await _loginService.DeleteLoginUserById(EditUser.Id);
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            return RedirectToPage("/Account/Index");
        }
    }
}

Pages/Account/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Account;
using AFCHIntranet.Models.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Account
{
    public class IndexModel : PageModel
    {
        private readonly LoginService _loginService;

        public IndexModel(LoginService loginService)
        {
            _loginService = loginService;
            this._loginService = loginService;
        }

        public async Task<IActionResult> OnGet()
        {
            var query = await _loginService.GetLoginUserList();
            if (!query.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }

            UserList = query.Value;
            return Page();
        }

        public List<LoginUser> UserList { get; set; }
    }
}

Pages/Staff/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Services;
using AFCHIntranet.Models.Staff;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Staff
{
    public class CreateModel : PageModel
    {
        private readonly StaffService _staffService;

        public CreateModel(StaffService staffService)
        {
            this._staffService = staffService;
        }

        public void OnGet()
        {
        }

        [BindProperty]
        public Staff_Detail Staff { get; set; }

        public async Task<IActionResult> OnPost()
        {
            var query = await _staffService.CreateNew(Staff);
            if (query.IsSuccess)
            {
                return RedirectToPage("Details", new { id = query.Staff.Id });
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
                return Page();
            }
        }
    }
}

Pages/Staff/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFCHIntranet.Models.Services;
using AFCHIntranet.Models.Staff;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AFCHIntranet.Pages.Staff
{
    public class EditModel : PageModel
    {
        private readonly StaffService _staffService;

        public EditModel(StaffService staffService)
        {
            this._staffService = staffService;
        }

        public async Task OnGet(int id)
        {
            var query = await _staffService.GetStaffById(id);
            if (query.IsSuccess)
            {
                Staff = query.Staff;
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
            }
        }

        [BindProperty]
        public Staff_Detail Staff { get; set; }

        public async Task<IActionResult> OnPostUpdateStaff()
        {
            var query = await _staffService.UpdateStaff(Staff);
            if (query.IsSuccess)
            {
                return RedirectToPage("Details", new { id = query.Staff.Id });
            }
            else
            {
                ModelState.AddModelError(string.Empty, query.Error);
                Staff = query.Staff;
                return Page();
            }
        }
    }
}

Pages/Account/Create.cshtml
@page
@model AFCHIntranet.Pages.Account.CreateModel
@{
}

<fieldset class="layui-elem-field layui-field-title">
    <legend>新增登录账号</legend>
</fieldset>

<div asp-validation-summary="All" class="layui-bg-red"></div>

<form class="layui-form" method="post">
    <div class="layui-form-item">
        <label class="layui-form-label">账号名</label>
        <div class="layui-input-inline">
            <input type="text" asp-for="NewUser.Name" lay-verify="required" lay-reqtext="用户名不能为空" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">密码</label>
        <div class="layui-input-inline">
            <input type="password" asp-for="NewUser.Password" lay-verify="required" lay-reqtext="密码不能为空" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">管理角色</label>
        <div class="layui-input-inline">
            <select asp-for="NewUser.RoleName">
                <option value="@LoginUserRole.User" selected>@LoginUserRole.User</option>
                <option value="@LoginUserRole.PowerUser">@LoginUserRole.PowerUser</option>
                <option value="@LoginUserRole.Administrator">@LoginUserRole.Administrator</option>
            </select>
        </div>
    </div>

    <div class="layui-form-item">
        <div class="layui-input-block">
            <button type="submit" class="layui-btn" lay-submit="">新增账号</button>
        </div>
    </div>
</form>

Pages/Account/Edit.cshtml
@page
@model AFCHIntranet.Pages.Account.EditModel
@{
}

<div asp-validation-summary="All" class="layui-bg-red"></div>

<fieldset class="layui-elem-field layui-field-box">
    <legend>编辑登录账号角色</legend>

    <form class="layui-form" method="post" asp-page-handler="EditUserRole">
        <input type="hidden" asp-for="EditUser.Id" />

        <div class="layui-form-item">
            <label class="layui-form-label">账号名</label>
            <div class="layui-input-inline">
                <input type="text" readonly asp-for="EditUser.Name" lay-verify="required" lay-reqtext="用户名不能为空" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">管理角色</label>
            <div class="layui-input-inline">
                <select asp-for="EditUser.RoleName">
                    <option value="@LoginUserRole.User">@LoginUserRole.User</option>
                    <option value="@LoginUserRole.PowerUser">@LoginUserRole.PowerUser</option>
                    <option value="@LoginUserRole.Administrator">@LoginUserRole.Administrator</option>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
                <button type="submit" class="layui-btn" lay-submit="">更改角色</button>
            </div>
        </div>
    </form>
</fieldset>


<fieldset class="layui-elem-field layui-field-box">
    <legend>更改登录账号密码</legend>

    <form class="layui-form" method="post" asp-page-handler="EditUserPassword">
        <input type="hidden" asp-for="EditUser.Id" />

        <div class="layui-form-item">
            <label class="layui-form-label">密码</label>
            <div class="layui-input-inline">
                <input type="password" asp-for="EditUser.Password" lay-verify="required" lay-reqtext="密码不能为空" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
                <button type="submit" class="layui-btn" lay-submit="">更改密码</button>
            </div>
        </div>
    </form>
</fieldset>


<fieldset class="layui-elem-field layui-field-box">
    <legend>删除登录账号</legend>

    <form class="layui-form" method="post" asp-page-handler="DeleteUser">
        <input type="hidden" asp-for="EditUser.Id" />

        <div class="layui-form-item">
            <div class="layui-input-block">
                <button type="submit" class="layui-btn" onclick="return DeleteUser()">删除账号</button>
            </div>
        </div>
    </form>
</fieldset>


@section Scripts{
    <script>


        function DeleteUser() {
            return confirm("确定删除账号?");
        }
    </script>
}

Pages/Account/Index.cshtml
@page
@model AFCHIntranet.Pages.Account.IndexModel
@{
}

<fieldset class="layui-elem-field layui-field-title">
    <legend>登录账号列表</legend>
</fieldset>

<div asp-validation-summary="ModelOnly" class="layui-bg-red"></div>

<table class="layui-table">
    <thead>
        <tr>
            <th>ID</th>
            <th>账号名</th>
            <th>角色</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var u in Model.UserList)
        {
            <tr>
                <td>@u.Id</td>
                <td>@u.Name</td>
                <td>@u.RoleName</td>
                <td>
                    <a asp-page="/Account/Edit" asp-route-id="@u.Id">编辑</a>
                </td>
            </tr>
        }
    </tbody>
</table>